# VS Code
acl allowed_domains dstdomain main.vscode-cdn.net
acl allowed_domains dstdomain marketplace.visualstudio.com
#acl allowed_domains dstdomain mobile.events.data.microsoft.com
acl allowed_domains dstdomain openai.gallerycdn.vsassets.io
#acl allowed_domains dstdomain 

#
# OpenAI / Codex
#

acl allowed_domains dstdomain .openai.com
acl allowed_domains dstdomain .chatgpt.com
acl allowed_domains dstdomain .oaistatic.com
acl allowed_domains dstdomain .oaiusercontent.com


#
# GitHub
#

acl allowed_domains dstdomain .github.com
acl allowed_domains dstdomain .githubusercontent.com


#
# npm
#

acl allowed_domains dstdomain registry.npmjs.org
